# Generated by Django 6.0.4 on 2026-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('nginx', 'Nginx'), ('pam', 'PAM'), ('app', 'Application')], max_length=20)),
                ('category', models.CharField(choices=[('auth_failure', 'Authentication Failure'), ('auth_success', 'Authentication Success'), ('access', 'Access'), ('error', 'Error')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.TextField()),
                ('parsed', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
