services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: siemlite
      POSTGRES_USER: siemlite
      POSTGRES_PASSWORD: siemlite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
